### ISSUE TITLE
after updating @sveltejs/vite-plugin-svelte from 3.1.2 to 4.0.0 `post.default.render()` is not a function

### ISSUE THREAD

**Issue by codebam** [pngwn/MDsveX#674]
https://github.com/codebam/seanbehan.ca/commit/308771994c7b7695e96cdbc063e5e49c027a7ba4

**Comment by codebam** [comment]
```
16:58:32.493    TypeError: post.default.render is not a function
16:58:32.494        at load (file:///opt/buildhome/repo/.svelte-kit/output/server/entries/pages/posts/_slug_/_page.server.ts.js:20:33)
16:58:32.494        at async load_server_data (file:///opt/buildhome/repo/.svelte-kit/output/server/index.js:586:18)
16:58:32.494        at async file:///opt/buildhome/repo/.svelte-kit/output/server/index.js:2035:18
16:58:32.498    TypeError: post.default.render is not a function
16:58:32.498        at load (file:///opt/buildhome/repo/.svelte-kit/output/server/entries/pages/posts/_slug_/_page.server.ts.js:20:33)
16:58:32.499        at async load_server_data (file:///opt/buildhome/repo/.svelte-kit/output/server/index.js:586:18)
16:58:32.499        at async file:///opt/buildhome/repo/.svelte-kit/output/server/index.js:2035:18
```

**Comment by codebam** [comment]
```
import { render } from 'svelte/server';
...
const { html } = render(post.default);
```
